"""Anthropic Claude API client for processing transferred data."""

import anthropic

CLAUDE_MODELS = [
    "claude-opus-4-6",
    "claude-sonnet-4-6",
    "claude-haiku-4-5-20251001",
]


def create_client(api_key: str) -> anthropic.Anthropic:
    """Create an Anthropic client with the provided key."""
    return anthropic.Anthropic(api_key=api_key)


def send_to_claude(
    client: anthropic.Anthropic,
    model: str,
    system_prompt: str,
    user_message: str,
    max_tokens: int = 4096,
) -> str:
    """Send a message to Claude and return the response text."""
    messages = [{"role": "user", "content": user_message}]
    kwargs = {
        "model": model,
        "max_tokens": max_tokens,
        "messages": messages,
    }
    if system_prompt:
        kwargs["system"] = system_prompt
    response = client.messages.create(**kwargs)
    return response.content[0].text


def transfer_with_context(
    client: anthropic.Anthropic,
    model: str,
    gemini_prompt: str,
    gemini_response: str,
    transfer_instruction: str,
    max_tokens: int = 4096,
) -> str:
    """Transfer Gemini data to Claude with context about the transfer."""
    system = (
        "You are receiving data that was originally generated by Google Gemini. "
        "Process it according to the user's instructions."
    )
    user_message = (
        f"## Original Prompt Sent to Gemini\n\n{gemini_prompt}\n\n"
        f"## Gemini's Response\n\n{gemini_response}\n\n"
        f"## Your Instructions\n\n{transfer_instruction}"
    )
    return send_to_claude(client, model, system, user_message, max_tokens)
